image: camdl/cudl-pack-pipelines:1.0.0
pipelines:
  default:
    - parallel:
        - step:
            name: Lint
            caches: [node]
            script:
              - npm install
              - npm run lint
        - step:
            name: Test
            caches: [node]
            script:
              - npm install
              - npm run test
