image: node:10.15
pipelines:
  default:
    - parallel:
        - step:
            name: Lint
            caches: [node]
            script:
              - npm install
              - npm run lint
        - step:
            name: Test
            caches: [node]
            script:
              - npm install
              - npm run test
