name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 17]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Install dependencies
        run: npm ci
      - run: npm run lint
      - run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Check code follows eslint rules
        run: npm run lint
      - name: Check files are auto-formatted with prettier
        run: npm run check-format
