name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install dependencies
        run: npm ci
      - run: npm run lint
      - run: npm test
